<?php

/**
 * Language entries for the module backend.
 */
$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8',

    'FOUN10_MODULES' => 'foun10',
    'FOUN10_EASYSEARCH' => 'Suche',
    'FOUN10_EASYSEARCH_ATTRIBUTES' => 'Attribute',
    'FOUN10_EASYSEARCH_SYNONYMS' => 'Synonyme',
    'FOUN10_EASYSEARCH_INDEX' => 'Index',
    'FOUN10_EASYSEARCH_LOG' => 'Auswertung',

    'FOUN10_EASYSEARCH_ADMIN_HEADLINE' => 'Suche - Attribute',
    'FOUN10_EASYSEARCH_ADMIN_INTRO' => 'Attribute per Drag & Drop zuordnen. Die Reihenfolge der Filter bestimmt, in welcher Reihenfolge sie im Shop angezeigt werden.',

    'FOUN10_EASYSEARCH_ADMIN_UNUSED' => 'Nicht zugeordnet',
    'FOUN10_EASYSEARCH_ADMIN_UNUSED_HINT' => 'Weder Filter noch durchsuchbar. Nach rechts ziehen, um sie zu verwenden.',
    'FOUN10_EASYSEARCH_ADMIN_CONFIGURED' => 'Konfiguriert',
    'FOUN10_EASYSEARCH_ADMIN_CONFIGURED_HINT' => 'Reihenfolge per Drag & Drop. Ein Attribut kann Filter und durchsuchbar zugleich sein - die Reihenfolge gilt für die Filterspalte im Shop. Anzeigename und Darstellung gelten nur für die Filterspalte.',
    'FOUN10_EASYSEARCH_ADMIN_ROLE_FACET' => 'Filter',
    'FOUN10_EASYSEARCH_ADMIN_ROLE_SEARCHABLE' => 'Durchsuchbar',
    'FOUN10_EASYSEARCH_ADMIN_DISPLAY' => 'Darstellung',
    'FOUN10_EASYSEARCH_ADMIN_DISPLAY_DEFAULT' => 'Standard (Liste)',
    'FOUN10_EASYSEARCH_ADMIN_DISPLAY_COLOR' => 'Farbkacheln',
    'FOUN10_EASYSEARCH_ADMIN_DISPLAY_GROUPEDCOLORTILE' => 'Farbkacheln, zu Farbgruppen zusammengefasst',
    'FOUN10_EASYSEARCH_ADMIN_LABEL' => 'Anzeigename',
    'FOUN10_EASYSEARCH_ADMIN_LABEL_PLACEHOLDER' => 'leer = Attributname',

    'FOUN10_EASYSEARCH_ADMIN_SAVE' => 'Speichern',
    'FOUN10_EASYSEARCH_ADMIN_SAVING' => 'Wird gespeichert …',
    'FOUN10_EASYSEARCH_ADMIN_SAVING_NOTE' => 'Die Liste wird anschließend neu aufgebaut - das dauert einen Moment.',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX' => 'Reindex starten',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_HINT' => 'Änderungen greifen im Shop erst nach einem Reindex. Es werden nur Produkte und Wörterbuch neu aufgebaut - der vollständige Aufbau liegt unter foun10 → Suche → Index.',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_RUNNING' => 'Index wird neu aufgebaut',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_CLEARING' => 'Alter Index wird entfernt …',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_PROGRESS' => '%1$s von %2$s Artikeln (Sprache %3$s)',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_CATEGORIES' => 'Kategorie-Zuordnungen werden aktualisiert …',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_DICTIONARY' => 'Wörterbuch wird aufgebaut …',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_DONE' => 'Fertig - %s Artikel indiziert.',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_DONE_CATEGORIES' => 'Fertig - %s Kategorie-Zuordnungen.',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_DONE_DICTIONARY' => 'Fertig - %s Begriffe im Wörterbuch.',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_DONE_SIMPLE' => 'Fertig.',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_FAILED' => 'Abgebrochen: %s',
    'FOUN10_EASYSEARCH_ADMIN_REINDEX_NOTE' => 'Das Fenster bitte offen lassen - der Aufbau läuft in kleinen Schritten über den Browser.',
    'FOUN10_EASYSEARCH_ADMIN_CLOSE' => 'Schließen',
    'FOUN10_EASYSEARCH_ADMIN_EMPTY' => 'Keine Attribute vorhanden.',

    'FOUN10_EASYSEARCH_SYNONYM_HEADLINE' => 'Suche - Synonyme',
    'FOUN10_EASYSEARCH_SYNONYM_INTRO' => 'Begriffe, die im Shop dasselbe finden sollen. Eine Regel braucht beide Seiten - Zeilen, bei denen Begriff oder Synonyme leer sind, werden beim Speichern verworfen. Die Regeln gelten je Subshop und je Sprache.',
    'FOUN10_EASYSEARCH_SYNONYM_LANGUAGE' => 'Sprache:',
    'FOUN10_EASYSEARCH_SYNONYM_LANGUAGE_HINT' => 'Synonyme gelten immer nur für die hier gewählte Sprache.',
    'FOUN10_EASYSEARCH_SYNONYM_SAVED' => 'Gespeichert - %s Regeln aktiv.',

    'FOUN10_EASYSEARCH_SYNONYM_TYPE' => 'Richtung',
    'FOUN10_EASYSEARCH_SYNONYM_TYPE_BOTH' => 'beide Richtungen',
    'FOUN10_EASYSEARCH_SYNONYM_TYPE_ONEWAY' => 'nur in diese Richtung',
    'FOUN10_EASYSEARCH_SYNONYM_TERM' => 'Begriff',
    'FOUN10_EASYSEARCH_SYNONYM_TERM_PLACEHOLDER' => 'z. B. BH',
    'FOUN10_EASYSEARCH_SYNONYM_SYNONYMS' => 'Synonyme',
    'FOUN10_EASYSEARCH_SYNONYM_SYNONYMS_PLACEHOLDER' => 'durch Komma getrennt, z. B. Büstenhalter, Bustier',
    'FOUN10_EASYSEARCH_SYNONYM_ACTIVE' => 'Aktiv',
    'FOUN10_EASYSEARCH_SYNONYM_REMOVE' => 'Zeile entfernen',
    'FOUN10_EASYSEARCH_SYNONYM_ADD' => 'Zeile hinzufügen',
    'FOUN10_EASYSEARCH_SYNONYM_NO_REINDEX' => 'Synonyme greifen sofort - dafür ist kein Reindex nötig.',
    'FOUN10_EASYSEARCH_SYNONYM_UNSAVED' => 'Es gibt ungespeicherte Änderungen. Beim Wechsel der Sprache gehen sie verloren. Trotzdem wechseln?',

    'FOUN10_EASYSEARCH_INDEX_HEADLINE' => 'Suche - Index',
    'FOUN10_EASYSEARCH_INDEX_INTRO' => 'Stand des Suchindex und Neuaufbau. Unten steht bei jedem Button, nach welcher Änderung er nötig ist - im Zweifel der komplette Neuaufbau ganz unten.',
    'FOUN10_EASYSEARCH_INDEX_LANGUAGE' => 'Sprache:',
    'FOUN10_EASYSEARCH_INDEX_LANGUAGE_HINT' => 'Status und Neuaufbau beziehen sich immer auf die hier gewählte Sprache.',
    'FOUN10_EASYSEARCH_INDEX_DOCUMENTS' => 'Produkte im Index',
    'FOUN10_EASYSEARCH_INDEX_CATEGORIES' => 'Kategorie-Zuordnungen',
    'FOUN10_EASYSEARCH_INDEX_TERMS' => 'Wörterbuch-Begriffe',
    'FOUN10_EASYSEARCH_INDEX_NEVER' => 'noch nie aufgebaut',
    'FOUN10_EASYSEARCH_INDEX_RUN_CATEGORIES' => 'Kategorien neu aufbauen',
    'FOUN10_EASYSEARCH_INDEX_RUN_DICTIONARY' => 'Wörterbuch neu aufbauen',
    'FOUN10_EASYSEARCH_INDEX_RUN_PRODUCTS' => 'Produkte neu aufbauen',
    'FOUN10_EASYSEARCH_INDEX_RUN_FULL' => 'Kompletten Index neu aufbauen',
    'FOUN10_EASYSEARCH_INDEX_TAKES_SECONDS' => 'wenige Sekunden',
    'FOUN10_EASYSEARCH_INDEX_TAKES_SHORT' => 'unter einer Minute',
    'FOUN10_EASYSEARCH_INDEX_TAKES_LONG' => 'mehrere Minuten',

    'FOUN10_EASYSEARCH_INDEX_WHEN_CATEGORIES' => 'Nötig, wenn sich geändert hat, in welchen Kategorien ein Produkt liegt. Läuft auch automatisch per Cron nach dem ERP-Import.',
    'FOUN10_EASYSEARCH_INDEX_WHEN_DICTIONARY' => 'Nötig, wenn die Suchvorschläge oder die Tippfehler-Korrektur veraltete Begriffe zeigen. Das Wörterbuch wird aus dem bestehenden Produktindex abgeleitet.',
    'FOUN10_EASYSEARCH_INDEX_WHEN_PRODUCTS' => 'Nötig, wenn sich Produktdaten geändert haben: Titel, Beschreibung, Artikelnummer, Preis, Bestand, <strong>Hersteller-Zuordnung</strong>, Attributwerte - oder welche Attribute als Filter bzw. durchsuchbar eingestellt sind.',
    'FOUN10_EASYSEARCH_INDEX_WHEN_FULL' => 'Produkte, Kategorien und Wörterbuch nacheinander. Der sichere Weg nach einem großen Import oder wenn unklar ist, was sich geändert hat.',

    'FOUN10_EASYSEARCH_INDEX_NO_REBUILD' => 'Ohne Neuaufbau sofort wirksam: Synonyme sowie Anzeigename und Darstellung der Attribute - die werden erst beim Suchen ausgewertet.',

    'FOUN10_EASYSEARCH_LOG_HEADLINE' => 'Suche - Auswertung',
    'FOUN10_EASYSEARCH_LOG_INTRO' => 'Was im Shop gesucht wurde, wie oft, und was nichts gefunden hat. Gezählt wird je Begriff und Tag - der kleinste Zeitraum ist damit ein Tag.',
    'FOUN10_EASYSEARCH_LOG_PERIOD' => 'Zeitraum:',
    'FOUN10_EASYSEARCH_LOG_PERIOD_DAY' => 'Heute',
    'FOUN10_EASYSEARCH_LOG_PERIOD_MONTH' => 'Laufender Monat',
    'FOUN10_EASYSEARCH_LOG_PERIOD_YEAR' => 'Laufendes Jahr',
    'FOUN10_EASYSEARCH_LOG_LANGUAGE' => 'Sprache:',
    'FOUN10_EASYSEARCH_LOG_LIMIT' => 'Einträge je Liste:',
    'FOUN10_EASYSEARCH_LOG_SHOW_SUSPICIOUS' => 'Aussortierte Eingaben anzeigen',
    'FOUN10_EASYSEARCH_LOG_EMPTY' => 'Fuer diesen Zeitraum und diese Sprache wurde noch nichts erfasst. Die Zahlen beginnen an dem Tag, an dem die Protokollierung aktiviert wurde.',

    'FOUN10_EASYSEARCH_LOG_KPI_SEARCHES' => 'Suchanfragen',
    'FOUN10_EASYSEARCH_LOG_KPI_TERMS' => 'Verschiedene Begriffe',
    'FOUN10_EASYSEARCH_LOG_KPI_TERMS_HINT' => 'ohne Mehrfachsuchen',
    'FOUN10_EASYSEARCH_LOG_KPI_ZERO' => 'Suchen ohne Treffer',
    'FOUN10_EASYSEARCH_LOG_KPI_ZERO_TERMS' => 'Begriffe ohne Treffer',
    'FOUN10_EASYSEARCH_LOG_KPI_ZERO_TERMS_HINT' => 'jeder davon ist eine Lücke',

    'FOUN10_EASYSEARCH_LOG_CHART' => 'Verlauf',
    'FOUN10_EASYSEARCH_LOG_CHART_CONTEXT' => 'Die helleren Balken liegen vor dem gewählten Tag und dienen nur dem Vergleich - die Zahlen oben beziehen sich allein auf heute.',
    'FOUN10_EASYSEARCH_LOG_SEARCHES' => 'Suchen',
    'FOUN10_EASYSEARCH_LOG_WITHOUT_HITS' => 'ohne Treffer',

    'FOUN10_EASYSEARCH_LOG_TOP' => 'Meistgesucht',
    'FOUN10_EASYSEARCH_LOG_TOP_HINT' => 'Die häufigsten Begriffe im gewählten Zeitraum. Treffer ist der Stand der letzten Suche nach diesem Begriff.',
    'FOUN10_EASYSEARCH_LOG_ZERO' => 'Ohne Treffer',
    'FOUN10_EASYSEARCH_LOG_ZERO_HINT' => 'Begriffe, die zuletzt nichts gefunden haben. Entweder fehlt dem Katalog das Wort - dann hilft ein Synonym - oder das Produkt.',
    'FOUN10_EASYSEARCH_LOG_TERM' => 'Begriff',
    'FOUN10_EASYSEARCH_LOG_COUNT' => 'Suchen',
    'FOUN10_EASYSEARCH_LOG_HITS' => 'Treffer',
    'FOUN10_EASYSEARCH_LOG_CORRECTION' => 'Vorschlag',
    'FOUN10_EASYSEARCH_LOG_LAST_SEEN' => 'Zuletzt',
    'FOUN10_EASYSEARCH_LOG_MAKE_SYNONYM' => 'Synonym anlegen',
    'FOUN10_EASYSEARCH_LOG_EDIT_SYNONYM' => 'Regel ansehen',
    'FOUN10_EASYSEARCH_LOG_SYNONYM_EXISTS' => 'Synonym vorhanden',
    'FOUN10_EASYSEARCH_LOG_ZERO_STALE' => 'Ein Begriff bleibt hier stehen, bis er erneut gesucht wurde - die Trefferzahl stammt immer aus der letzten Suche. Ein gerade angelegtes Synonym wirkt also sofort im Shop, aber in dieser Liste erst nach der nächsten Suche.',
    'FOUN10_EASYSEARCH_LOG_NONE' => 'Keine Einträge.',
    'FOUN10_EASYSEARCH_LOG_ZERO_NONE' => 'Jeder erfasste Begriff hat etwas gefunden.',

    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_HIDDEN' => '%s Eingaben sind ausgeblendet, weil sie keine Suchbegriffe sind (Angriffsversuche, URLs, Codefragmente). Neue dieser Art werden gar nicht erst gespeichert.',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_CONTROL' => 'Steuerzeichen',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_MARKUP' => 'HTML/Script',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_SQL' => 'SQL',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_PATH' => 'Pfad',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_TEMPLATE' => 'Template',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_SHELL' => 'Shell',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_URL' => 'URL',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_LENGTH' => 'zu lang',
    'FOUN10_EASYSEARCH_LOG_SUSPICIOUS_SYMBOLS' => 'Sonderzeichen',

    'FOUN10_EASYSEARCH_LOG_PRIVACY' => 'Erfasst werden nur die Wörter selbst, je Tag gezählt - keine Sitzung, keine IP-Adresse, nichts, was zu einer Person zurückführt.',

    'FOUN10_EASYSEARCH_LOG_MONTH_1' => 'Januar',
    'FOUN10_EASYSEARCH_LOG_MONTH_2' => 'Februar',
    'FOUN10_EASYSEARCH_LOG_MONTH_3' => 'März',
    'FOUN10_EASYSEARCH_LOG_MONTH_4' => 'April',
    'FOUN10_EASYSEARCH_LOG_MONTH_5' => 'Mai',
    'FOUN10_EASYSEARCH_LOG_MONTH_6' => 'Juni',
    'FOUN10_EASYSEARCH_LOG_MONTH_7' => 'Juli',
    'FOUN10_EASYSEARCH_LOG_MONTH_8' => 'August',
    'FOUN10_EASYSEARCH_LOG_MONTH_9' => 'September',
    'FOUN10_EASYSEARCH_LOG_MONTH_10' => 'Oktober',
    'FOUN10_EASYSEARCH_LOG_MONTH_11' => 'November',
    'FOUN10_EASYSEARCH_LOG_MONTH_12' => 'Dezember',

    'FOUN10_EASYSEARCH_SYNONYM_PREFILLED' => 'Der Begriff "%s" wurde aus der Auswertung übernommen - Synonyme eintragen und speichern.',

    // --- Moduleinstellungen -------------------------------------------------
    //
    // Die Schlüssel sind von OXID vorgegeben: SHOP_MODULE_GROUP_<gruppe> für die
    // Überschrift, SHOP_MODULE_<NAME> für das Feld, SHOP_MODULE_<NAME>_<wert>
    // für die Optionen eines Auswahlfelds und HELP_SHOP_MODULE_<NAME> für den
    // Hilfetext hinter dem Fragezeichen.

    'SHOP_MODULE_GROUP_foun10easysearch_engine' => 'Suchmaschine',
    'SHOP_MODULE_GROUP_foun10easysearch_correction' => 'Fehlertoleranz',
    'SHOP_MODULE_GROUP_foun10easysearch_display' => 'Anzeige im Shop',
    'SHOP_MODULE_GROUP_foun10easysearch_facets' => 'Filter',
    'SHOP_MODULE_GROUP_foun10easysearch_suggest' => 'Suggest',

    'SHOP_MODULE_FOUN10EASYSEARCH_ENGINE' => 'Suchmaschine',
    'SHOP_MODULE_FOUN10EASYSEARCH_ENGINE_mysql' => 'MySQL - die Shop-Datenbank',
    'SHOP_MODULE_FOUN10EASYSEARCH_ENGINE_meilisearch' => 'Meilisearch - eigener Suchdienst',
    'SHOP_MODULE_FOUN10EASYSEARCH_ENGINE_null' => 'Aus - die Standardsuche des Shops',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_ENGINE' => 'Welcher Dienst die Suche beantwortet. Der gewählte Index muss aufgebaut sein - solange er fehlt, meldet sich das Modul als nicht verfügbar und der Shop sucht selbst. Nach dem Umstellen einen Reindex laufen lassen.',

    'SHOP_MODULE_FOUN10EASYSEARCH_MEILI_HOST' => 'Meilisearch: Adresse',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_MEILI_HOST' => 'Nur als Rückfalloption. Ist die Umgebungsvariable MEILI_HOST gesetzt, gilt diese - so bekommt jede Umgebung ihren eigenen Server, ohne dass hier etwas steht.',
    'SHOP_MODULE_FOUN10EASYSEARCH_MEILI_KEY' => 'Meilisearch: API-Schlüssel',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_MEILI_KEY' => 'Nur als Rückfalloption, wie die Adresse: MEILI_MASTER_KEY aus der Umgebung hat Vorrang.',
    'SHOP_MODULE_FOUN10EASYSEARCH_MEILI_PREFIX' => 'Meilisearch: Index-Präfix',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_MEILI_PREFIX' => 'Vorsatz der Indexnamen, leer bedeutet foun10easysearch. Nötig, wenn sich mehrere Installationen einen Meilisearch-Server teilen.',

    'SHOP_MODULE_FOUN10EASYSEARCH_LOG_ENABLED' => 'Suchbegriffe protokollieren',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_LOG_ENABLED' => 'Zählt je Tag, welche Begriffe gesucht wurden und wie viele Treffer sie hatten - die Grundlage der Auswertung. Gespeichert werden nur die Wörter, nichts, was zu einer Person zurückführt.',
    'SHOP_MODULE_FOUN10EASYSEARCH_PARENT_ATTRIBUTES' => 'Attribute des Hauptartikels mitverwenden',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_PARENT_ATTRIBUTES' => 'Aus: Eine Variante wird nur mit ihren eigenen Attributen indiziert. An: Sie erbt zusätzlich die Attribute des Hauptartikels. Das ist nur sinnvoll, wenn am Hauptartikel steht, was für alle Varianten gilt (etwa Material). Stehen dort - wie bei diesem Warenwirtschaftsimport - alle Werte der Varianten zusammen, dann hätte jede Variante plötzlich alle Cup-Größen ihrer Geschwister und der Filter wäre wertlos. Nach dem Umstellen ist ein Neuaufbau des Index nötig.',
    'SHOP_MODULE_FOUN10EASYSEARCH_MIN_TERM_LENGTH' => 'Mindestlänge eines Suchbegriffs',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_MIN_TERM_LENGTH' => 'Kürzere Eingaben werden nicht gesucht.',

    'SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_ENABLED' => 'Tippfehler korrigieren',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_ENABLED' => 'Vergleicht den Suchbegriff mit dem Wörterbuch aus dem Index und schlägt ein ähnliches Wort vor.',
    'SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_AUTO_APPLY' => 'Korrektur direkt anwenden',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_AUTO_APPLY' => 'An: Es werden sofort die Treffer des korrigierten Begriffs gezeigt, der Hinweis darüber nennt beide Begriffe. Aus: Die Trefferliste bleibt die der Kundschaft, und der Hinweis fragt "Meinten Sie ...?". Sichtbar ist er in beiden Fällen nur, wenn "Korrekturhinweis über der Trefferliste anzeigen" an ist.',
    'SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_MAX_HITS' => 'Korrigieren bis zu dieser Trefferzahl',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_MAX_HITS' => '0 bedeutet: nur korrigieren, wenn gar nichts gefunden wurde. Ein höherer Wert korrigiert auch dann, wenn die Suche nur wenige Treffer hat.',
    'SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_MIN_FREQUENCY' => 'Mindesthäufigkeit des Zielbegriffs',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_CORRECTION_MIN_FREQUENCY' => 'Es wird nie auf ein Wort korrigiert, das im Katalog seltener vorkommt als hier angegeben - sonst führt ein Tippfehler im Katalog die Kundschaft in die Irre.',

    'SHOP_MODULE_FOUN10EASYSEARCH_SHOW_CORRECTION' => 'Korrekturhinweis über der Trefferliste anzeigen',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_SHOW_CORRECTION' => 'Der Hinweis hat zwei Formen, und welche erscheint, entscheidet "Korrektur direkt anwenden": ist die an, steht dort "Keine Ergebnisse für ... stattdessen ..." mit einem Link zurück zum eingegebenen Begriff. Nur wenn sie aus ist, erscheint "Meinten Sie ...?". Ist dieser Schalter hier aus, korrigiert die Suche weiterhin, sagt es der Kundschaft aber nicht.',

    'SHOP_MODULE_FOUN10EASYSEARCH_FACET_VALUE_LIMIT' => 'Werte je Filter',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_FACET_VALUE_LIMIT' => 'Wie viele Werte ein Filter in der Filterspalte höchstens anzeigt.',

    'SHOP_MODULE_FOUN10EASYSEARCH_SUGGEST_LIMIT_TERMS' => 'Begriffe im Suggest Flyout',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_SUGGEST_LIMIT_TERMS' => 'Anzahl der Wortvorschläge, die das Suggest Flyout unter dem Suchfeld anzeigt.',
    'SHOP_MODULE_FOUN10EASYSEARCH_SUGGEST_LIMIT_PRODUCTS' => 'Produkte im Suggest Flyout',
    'HELP_SHOP_MODULE_FOUN10EASYSEARCH_SUGGEST_LIMIT_PRODUCTS' => 'Anzahl der Produkte, die das Suggest Flyout mit Bild und Preis anzeigt.',
];
